#!/bin/bash

# TODO: check requirements first, from here
# cf: ./.Project_Xs/install_requirements.bash

# BLINK TIMER spreadsheet: https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbUxleER4WmZVd1hESlFTbVA1elJlNkladFFrZ3xBQ3Jtc0trTkdUU0UzQnNnWXdqQWRaeG53R2gyOFZTbGRaLWxqenNhV19JTlRGQ1VsVy16RFc2bFU1dFR6VXNNc3lianNGWm5kOGw0TjZmRjZkRS0tNmt0Mjk2ZklHUXp2Nll3bFBnY1RQd3lNWWtKR0EzaHJpUQ&q=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1mE3UH2lAJBV-VZaaFh5cJMt0tiVH-x43T5YnrNxDYxc%2Fedit%3Fusp%3Dsharing&v=6tbCmEt5Nr8
python ./.Project_Xs/src/player_blink_gui.py

# TODO: better UI, and update to Python 3.12 ?
# -> JS UI (rather than Tkinter), communicating with Python app via Websockets
